INFO:root:bot has started
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\ext\extbot.py", line 222, in get_updates
    updates = super().get_updates(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 2861, in get_updates
    self._post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\bot.py", line 295, in _post
    return self.request.post(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 356, in post
    result = self._request_wrapper(
  File "D:\”л√“”\олимпиады\хакатон\tinder\venv\lib\site-packages\telegram\utils\request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
